export type SiteConfig = typeof siteConfig;

export const siteConfig = {
	name: "Otakudesu API",
	description: "Generated by Rizky Haksono",
	headerItems: [
		{
			label: "Docs",
			href: "https://otakudesu-docs.vercel.app/docs/intro",
		},
    {
      label: "GitHub",
      href: "https://github.com/rizkyhaksono",
    },
	],
	footerItems: [
		{
			label: "Home",
			href: "/",
		},
    {
      label: "About",
      href: "/about",
    },
    {
      label: "Contact",
      href: "/contact",
    }
	],
	links: {
		github: "https://github.com/rizkyhaksono",
		twitter: "https://twitter.com/rizkyhaksono"
	},
};